export enum MetaEvent {
  AddPaymentInfo = "AddPaymentInfo",
  AddToCart = "AddToCart",
  AddToWishlist = "AddToWishlist",
  CompleteRegistration = "CompleteRegistration",
  Contact = "Contact",
  CustomizeProduct = "CustomizeProduct",
  Donate = "Donate",
  FindLocation = "FindLocation",
  InitiateCheckout = "InitiateCheckout",
  Lead = "Lead",
  Purchase = "Purchase",
  Schedule = "Schedule",
  Search = "Search",
  StartTrial = "StartTrial",
  SubmitApplication = "SubmitApplication",
  Subscribe = "Subscribe",
  ViewContent = "ViewContent",
  PageView = "PageView"
}